// <auto-generated />
using Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace SATIoT.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220405065814_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Entities.AppObjassoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("AssocText")
                        .HasColumnType("text");

                    b.Property<int>("ChildId")
                        .HasColumnType("integer");

                    b.Property<string>("ChildType")
                        .HasColumnType("text");

                    b.Property<int>("ParentId")
                        .HasColumnType("integer");

                    b.Property<string>("ParentType")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AppObjassoc");
                });

            modelBuilder.Entity("Entities.AppObject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("ObjDesc")
                        .HasColumnType("text");

                    b.Property<string>("ObjName")
                        .HasColumnType("text");

                    b.Property<string>("ObjText")
                        .HasColumnType("text");

                    b.Property<string>("ObjType")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AppObject");
                });
#pragma warning restore 612, 618
        }
    }
}
