// <auto-generated />
using Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace SATIoT.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Entities.AppObjassoc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AssocText")
                        .HasColumnType("TEXT");

                    b.Property<int>("ChildId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChildType")
                        .HasColumnType("TEXT");

                    b.Property<int>("ParentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ParentType")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AppObjassoc");
                });

            modelBuilder.Entity("Entities.AppObject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ObjDesc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ObjName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ObjText")
                        .HasColumnType("TEXT");

                    b.Property<string>("ObjType")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AppObject");
                });
#pragma warning restore 612, 618
        }
    }
}
